apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: deploy
  labels:
          app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: hello-app
        image: ismailramadan/hello-pythonapp:latest


