apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
          app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: web-app
    spec:
      containers:
      - name: hello-app
        image: ismailramadan/hello-pythonapp:latest


apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 8080
      targetPort: 8080