apiVersion: v1
kind: Service
metadata:
  namespace: deploy
  name: myservice
  annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 8000
      targetPort: 8000